# Generated by Django 5.0.2 on 2024-04-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_animal', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascostas.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='FichaDesparasitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('desparasitante', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=255)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascostas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascostas.dueno')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascostas.mascota')),
            ],
        ),
    ]
